// build_full_guide.js
const fs = require('fs');
const path = require('path');

const { generateServerSection } = require('./section2_server');
const { generateSharedSection } = require('./section3_shared');
const { generatePagesSection } = require('./section4_pages');
const { generateAdminSection } = require('./section5_admin');
const { generateSecurityAndAlgorithmsSections } = require('./section6_7');

const ROOT = __dirname;
const GUIDE_PATH = path.join(ROOT, 'guide.txt');

console.log("=== COMPILING COMPLETE EXHAUSTIVE TECHNICAL GUIDE ===");

let guideParts = [];

// Header & Section 1
guideParts.push("================================================================================");
guideParts.push("ENERGY TAP REACTOR & REWARDS PLATFORM - COMPLETE EXHAUSTIVE TECHNICAL GUIDE");
guideParts.push("CODEBASE ARCHITECTURE, MODULAR PIPELINES & FUNCTION SPECIFICATIONS");
guideParts.push("================================================================================");
guideParts.push("Format: Pure Plain Text (.txt)");
guideParts.push("Scope: Every Page, Every Module, Every Function, and Line-by-Line Architecture");
guideParts.push("Generated: September 2026");
guideParts.push("================================================================================");
guideParts.push("");
guideParts.push("TABLE OF CONTENTS");
guideParts.push("--------------------------------------------------------------------------------");
guideParts.push("1. EXECUTIVE ARCHITECTURE & REPOSITORY BLUEPRINT");
guideParts.push("   1.1 Core Technology Stack & Runtime Ecosystem");
guideParts.push("   1.2 Complete Directory Structure & File Map");
guideParts.push("   1.3 Modular Component Lifecycle & The Assemble Engine (assemble.js)");
guideParts.push("   1.4 Admin Assembly Engine (admin/assemble.js)");
guideParts.push("");
guideParts.push("2. BACKEND SERVER ARCHITECTURE (server.js)");
guideParts.push("   2.1 Architecture, Dependencies & Port Binding");
guideParts.push("   2.2 MIME Types & File Serving Security");
guideParts.push("   2.3 In-Memory Data Store (memoryStore) Schema");
guideParts.push("   2.4 Identity Normalization & Utility Functions");
guideParts.push("   2.5 Authentication & Multi-Identity Management API Endpoints");
guideParts.push("   2.6 Level 1-1000 Configuration & Progression API Endpoints");
guideParts.push("   2.7 Tasks, Users & Administration API Endpoints");
guideParts.push("   2.8 Cashout & Account Requests Processing API Endpoints");
guideParts.push("   2.9 In-Game Notification Center Broadcast APIs (/api/notifications)");
guideParts.push("   2.10 Anti-Fraud & Server-Authoritative Reward Claim API (/api/reward/claim)");
guideParts.push("   2.11 Tap Velocity Anomaly & Autoclicker Detection API (/api/anti-fraud/verify-tap-session)");
guideParts.push("   2.12 Static Asset Delivery Pipeline & Path Sanitization");
guideParts.push("");
guideParts.push("3. FRONTEND CORE & SHARED CLIENT SERVICES (frontend/shared/)");
guideParts.push("   3.1 Reactive Game State & Server Authority Engine (frontend/shared/state.js)");
guideParts.push("   3.2 Application Controller, Router & In-Game Notification Center (frontend/shared/app.js)");
guideParts.push("   3.3 Cloud Database & Realtime Synchronization (frontend/shared/firebase-service.js)");
guideParts.push("   3.4 Ad Network Integration & Simulator (frontend/shared/ad-service.js)");
guideParts.push("   3.5 Global Design System & Cyber Theme Tokens (frontend/shared/common.css)");
guideParts.push("");
guideParts.push("4. DEEP-DIVE INTO ALL 27 FRONTEND PAGES (frontend/pages/)");
guideParts.push("   4.1  Home Page (home) - Quantum Reactor Core");
guideParts.push("   4.2  Energy Page (energy) - 7-Tier Fuel Injector & Booster");
guideParts.push("   4.3  Tasks Page (tasks) - Social Missions & Verification Timers");
guideParts.push("   4.4  Profile Page (profile) - Player Identity, 13 Metrics & 5 Achievement Badges");
guideParts.push("   4.5  XP Page (xp) - 1 to 1000 Level Roadmaps & 10,000 Coin Cash Prize");
guideParts.push("   4.6  Reward Page (reward) - Cyber Arcade & Mini-Game Hub");
guideParts.push("   4.7  Goal Page (goal) - 1 to 1000 Milestones & Mega Goal Prize");
guideParts.push("   4.8  Streak Page (streak) - Consecutive Login Matrix");
guideParts.push("   4.9  Mega Reward Page (mega-reward) - High-Roller Challenges");
guideParts.push("   4.10 Gift Card Page (gift-card) - Store Voucher Redemption");
guideParts.push("   4.11 Gadgets Page (gadgets) - Tech Hardware Marketplace");
guideParts.push("   4.12 Accessories Page (accessories) - Visual Skins & Custom Rings");
guideParts.push("   4.13 Gaming Tool Page (gaming-tool) - CPS Speed Analyzer & Utilities");
guideParts.push("   4.14 Kitchen Page (kitchen) - Lifestyle Goods Catalog");
guideParts.push("   4.15 Stationery Page (stationery) - Office & Creative Supplies");
guideParts.push("   4.16 Fitness Page (fitness) - Health & Athletic Equipment");
guideParts.push("   4.17 Home Decorate Page (home-decorate) - Ambient Living Products");
guideParts.push("   4.18 Custom Page (custom) - Bespoke Orders & Exclusive Perks");
guideParts.push("   4.19 Suggest Box Page (suggest-box) - Feedback & Polling Engine");
guideParts.push("   4.20 Ad Rewards Page (ad-rewards) - Direct Monetag Ad Booster");
guideParts.push("   4.21 Spin Page (spin) - Lucky Rotary Wheel (HTML5 Canvas)");
guideParts.push("   4.22 Chest Page (chest) - 4-Tier Mystery Vaults");
guideParts.push("   4.23 Scratch Page (scratch) - Quantum Scratch Card (Card Lock, Foil Erase & 5 Prize Tiers)");
guideParts.push("   4.24 Egg Page (egg) - 12-Egg Cyber Hatchery (10 Random + 11th Hatch Match-3 Win)");
guideParts.push("   4.25 Leaderboard Page (leaderboard) - Global Realtime Rankings");
guideParts.push("   4.26 Memory Match Page (memory-match) - 4x4 Grid, Timer, Mistake Scaling & Authoritative Rewards");
guideParts.push("   4.27 Coin Catcher Page (coin-catcher) - Falling Coins & Bombs, 3-Life Meter, Combo Multipliers & Server Bounds");
guideParts.push("");
guideParts.push("5. ADMIN PORTAL MODULES & CONTROL CENTER (admin/)");
guideParts.push("   5.1 Admin Architecture & Modular Pipeline");
guideParts.push("   5.2 Dashboard Module (admin/pages/dashboard/) - Added In-Game Notification Center Broadcaster");
guideParts.push("   5.3 User Management Module (admin/pages/users/)");
guideParts.push("   5.4 Account Verification Module (admin/pages/account-requests/)");
guideParts.push("   5.5 Ad Network Configuration Module (admin/pages/ads-manage/)");
guideParts.push("   5.6 Firebase Control Module (admin/pages/firebase-manage/)");
guideParts.push("   5.7 Mega Reward Creation Module (admin/pages/mega-add/)");
guideParts.push("   5.8 Mega Payout Processing Module (admin/pages/mega-request/)");
guideParts.push("   5.9 Global System Settings Module (admin/pages/settings/)");
guideParts.push("   5.10 Web & Social Tasks Control Module (admin/pages/tasks-web/)");
guideParts.push("   5.11 Admin Firebase SDK Bridge (admin/shared/firebase.js)");
guideParts.push("");
guideParts.push("6. SECURITY RULES & CONFIGURATIONS");
guideParts.push("   6.1 Firebase Realtime Database Security (database.rules.json)");
guideParts.push("   6.2 Cloud Firestore Security (firestore.rules)");
guideParts.push("   6.3 Cloud Hosting & Rewrites (firebase.json & vercel.json)");
guideParts.push("");
guideParts.push("7. END-TO-END EXECUTION FLOWS & ALGORITHMIC PROOFS");
guideParts.push("   7.1 Tap Execution & Power Consumption Flow");
guideParts.push("   7.2 XP Level Advance & Dark Green Fuel Math (Levels 1 to 1000)");
guideParts.push("   7.3 Goal Milestone Progression & Exponential Scaling (Goals 1 to 1000)");
guideParts.push("   7.4 Scratch Card Foil Alpha Subsampling Math & 5-Tier Probabilities");
guideParts.push("   7.5 12-Egg Hatchery Pigeonhole Randomization & 11th Hatch Victory Proof");
guideParts.push("   7.6 Anti-Fraud Ad Verification & Multi-Device Account Unification");
guideParts.push("   7.7 Memory Match Timing Math, Speed Bonus & Star Rating Proofs");
guideParts.push("   7.8 Coin Catcher Physics, Hazards, Combo Multiplier & Score Bounds");
guideParts.push("   7.9 In-Game Notification Dispatch, Inbox Persistence & Deep-Link Routing");
guideParts.push("   7.10 Anti-Fraud Engine: Replay Prevention, Cooldowns & Autoclicker Anomaly Detection");
guideParts.push("   7.11 Server-Authoritative vs Client-Authoritative Architectural Separation");
guideParts.push("================================================================================");
guideParts.push("");

// Section 1
guideParts.push("================================================================================");
guideParts.push("SECTION 1: EXECUTIVE ARCHITECTURE & REPOSITORY BLUEPRINT");
guideParts.push("================================================================================");
guideParts.push("");
guideParts.push("1.1 CORE TECHNOLOGY STACK & RUNTIME ECOSYSTEM");
guideParts.push("- Runtime: Node.js (v18+ LTS recommended). Pure native HTTP server with zero heavyweight frameworks.");
guideParts.push("- Client: Pure Vanilla HTML5, CSS3, and ES6+ JavaScript. No React, Vue, or Angular bundle bloat.");
guideParts.push("  This ensures instantaneous load times under 500ms on mobile devices and 60 FPS tap responsiveness.");
guideParts.push("- Graphics: HTML5 2D Canvas context utilized for interactive scratch card foil erasing (scratch.js)");
guideParts.push("  and physics-driven rotary wheel deceleration (spin.js).");
guideParts.push("- Procedural Audio: HTML5 Web Audio API (AudioContext) procedural synthesis. Sound effects (square, sine,");
guideParts.push("  sawtooth waves) are generated dynamically with custom ADSR envelopes, eliminating audio asset downloads.");
guideParts.push("- Telegram Mini App: Native Telegram WebApp SDK (telegram-web-app.js) integration for automatic user context,");
guideParts.push("  theme synchronization, and native mobile haptic feedback.");
guideParts.push("- Monetization: Monetag Rewarded Interstitial SDK (Zone 11677609) with automated fallback to an internal");
guideParts.push("  5-second simulated ad countdown player when adblockers or network restrictions occur.");
guideParts.push("- Dual Cloud Database: Bidirectional synchronization with Google Firebase Realtime Database and Cloud");
guideParts.push("  Firestore, backed by local Node.js in-memory caching and localStorage persistence.");
guideParts.push("");
guideParts.push("1.2 DIRECTORY STRUCTURE & FILE MAP");
guideParts.push("d:\\project\\tap gmae\\new\\");
guideParts.push("|-- server.js                         : Master Node.js HTTP server and REST API engine.");
guideParts.push("|-- package.json                      : Node project dependencies and lifecycle scripts.");
guideParts.push("|-- assemble.js                       : Top-level build pipeline executing frontend assembly.");
guideParts.push("|-- database.rules.json               : Firebase Realtime Database security rules.");
guideParts.push("|-- firestore.rules                   : Google Cloud Firestore security rules.");
guideParts.push("|-- firebase.json                     : Firebase Hosting, Rewrites, and Emulator configuration.");
guideParts.push("|-- vercel.json                       : Vercel serverless deployment and API routing configuration.");
guideParts.push("|-- guide.txt                         : This exhaustive technical manual.");
guideParts.push("|");
guideParts.push("|-- frontend/                         : Player Client Single Page Application (SPA).");
guideParts.push("|   |-- index.html                    : Master compiled client SPA containing all 27 page views.");
guideParts.push("|   |-- assemble.js                   : Compiler script that scans, verifies, and stitches 27 pages.");
guideParts.push("|   |-- style.css                     : Top-level stylesheet importing shared and page styles.");
guideParts.push("|   |-- shared/                       : Core client engines and services.");
guideParts.push("|   |   |-- state.js                  : Central reactive gameState store, local persistence & server authority.");
guideParts.push("|   |   |-- app.js                    : App bootstrapper, DOM cache, router, audio, toasts & Notification Center.");
guideParts.push("|   |   |-- firebase-service.js       : Realtime Database & Firestore sync engine.");
guideParts.push("|   |   |-- ad-service.js             : Monetag SDK integration and fallback simulator.");
guideParts.push("|   |   |-- common.css                : Global CSS variables, design tokens, and cyber theme.");
guideParts.push("|   |-- pages/                        : 27 modular self-contained page components.");
guideParts.push("|       |-- home/                     : Central Quantum Reactor, tap engine, click floaters.");
guideParts.push("|       |-- energy/                   : 7-tier fuel injector, generator upgrades, turbo timer.");
guideParts.push("|       |-- tasks/                    : Social, YouTube, Telegram & partner web missions.");
guideParts.push("|       |-- profile/                  : Player profile, 13 operational metrics & 5 achievement badges.");
guideParts.push("|       |-- xp/                       : Levels 1-1000 roadmap & 10,000 Coins Mega Cash Prize.");
guideParts.push("|       |-- reward/                   : Cyber arcade hub linking to all mini-games.");
guideParts.push("|       |-- goal/                     : Goals 1-1000 roadmap & Level 1000 Mega Goal Prize.");
guideParts.push("|       |-- streak/                   : Daily login check-in matrix & streak freeze.");
guideParts.push("|       |-- mega-reward/              : Progressive community jackpot challenges.");
guideParts.push("|       |-- gift-card/                : Google Play, Amazon, and Steam voucher store.");
guideParts.push("|       |-- gadgets/                  : Tech gadgets, smartphones, and hardware rewards.");
guideParts.push("|       |-- accessories/              : Cosmetic reactor ring skins and particle glows.");
guideParts.push("|       |-- gaming-tool/              : CPS (clicks per second) speed diagnostic utility.");
guideParts.push("|       |-- kitchen/                  : Lifestyle and kitchenware reward catalog.");
guideParts.push("|       |-- stationery/               : Academic, school, and creative office supplies catalog.");
guideParts.push("|       |-- fitness/                  : Athletic equipment, gym gear, and health wellness catalog.");
guideParts.push("|       |-- home-decorate/            : Ambient interior decor, smart lighting, and room aesthetic catalog.");
guideParts.push("|       |-- custom/                   : Bespoke reward order portal for exclusive player requests.");
guideParts.push("|       |-- suggest-box/              : Community feedback, game feature voting, and player suggestion submitter.");
guideParts.push("|       |-- ad-rewards/               : Direct rewarded video ad station for instant energy refill.");
guideParts.push("|       |-- spin/                     : Lucky rotary wheel mini-game rendered on HTML5 Canvas.");
guideParts.push("|       |-- chest/                    : 4-tier mystery vault mini-game (Bronze, Silver, Gold, Cyber).");
guideParts.push("|       |-- scratch/                  : Quantum Scratch Card (Card lock, foil erase & 5 prize tiers).");
guideParts.push("|       |-- egg/                      : 12-Egg Cyber Hatchery (10 random non-winning + 11th hatch win).");
guideParts.push("|       |-- leaderboard/              : Global player rankings across total coins and levels.");
guideParts.push("|       |-- memory-match/             : 4x4 Memory Match card game (16 cards, 8 pairs, timer, rewards).");
guideParts.push("|       |-- coin-catcher/             : Dynamic coin catcher (falling coins/bombs, combo meter, 3 lives).");
guideParts.push("|");
guideParts.push("|-- admin/                            : Administrative Web Portal.");
guideParts.push("|   |-- index.html                    : Master compiled admin dashboard.");
guideParts.push("|   |-- assemble.js                   : Admin compiler stitching 9 administrative modules.");
guideParts.push("|   |-- shared/                       : Shared admin modules.");
guideParts.push("|   |   |-- firebase.js               : Admin Firebase SDK bridge with elevated privileges.");
guideParts.push("|   |   |-- common.css                : Admin control styling and data tables.");
guideParts.push("|   |-- pages/                        : 9 administrative control modules.");
guideParts.push("|       |-- dashboard/                : Platform analytics, active sessions, coin circulation.");
guideParts.push("|       |-- users/                    : Player search, balance modifier, ban/unban toggles.");
guideParts.push("|       |-- account-requests/         : Multi-identity conflict review & approval.");
guideParts.push("|       |-- ads-manage/               : Monetag zone IDs, cooldowns, and daily caps.");
guideParts.push("|       |-- firebase-manage/          : Cloud backup export, JSON restore, collection wipes.");
guideParts.push("|       |-- mega-add/                 : Custom jackpot / lottery creator.");
guideParts.push("|       |-- mega-request/             : Payout review for Level 1000 Cash Prizes (UPI/Paytm).");
guideParts.push("|       |-- settings/                 : Maintenance mode, emergency banner, Level 1-1000 editor.");
guideParts.push("|       |-- tasks-web/                : Partner website and social tasks manager.");
guideParts.push("");
guideParts.push("1.3 MODULAR COMPONENT LIFECYCLE & THE ASSEMBLE ENGINE (frontend/assemble.js)");
guideParts.push("Each page is developed across 3 files: <page>.html, <page>.css, and <page>.js.");
guideParts.push("The assemble script (node frontend/assemble.js):");
guideParts.push("  1. Verifies that all 3 files exist for each of the 27 pages.");
guideParts.push("  2. Injects meta tags, SDK scripts, fonts, and stylesheets into the compiled <head>.");
guideParts.push("  3. Concatenates all 27 page HTML fragments into the <main> container.");
guideParts.push("  4. Injects persistent header pills and floating cyber bottom navigation.");
guideParts.push("  5. Concatenates all shared and page JavaScript scripts into frontend/index.html.");
guideParts.push("");
guideParts.push("1.4 ADMIN ASSEMBLY ENGINE (admin/assemble.js)");
guideParts.push("Compiles the 9 administrative modules into admin/index.html with top navigation tabs and administrative controls.");
guideParts.push("");

console.log("Adding Section 2...");
guideParts.push(generateServerSection());

console.log("Adding Section 3...");
guideParts.push(generateSharedSection());

console.log("Adding Section 4 (all 27 pages)...");
guideParts.push(generatePagesSection());

console.log("Adding Section 5 (all 9 admin modules)...");
guideParts.push(generateAdminSection());

console.log("Adding Section 6 & 7...");
guideParts.push(generateSecurityAndAlgorithmsSections());

const fullText = guideParts.join('\n');
fs.writeFileSync(GUIDE_PATH, fullText, 'utf8');

console.log(`Successfully generated guide.txt!`);
console.log(`Total Length: ${fullText.length} characters`);
console.log(`Total Lines : ${fullText.split('\n').length} lines`);
