// section2_server.js
// Generates in-depth text for server.js
function generateServerSection() {
  let s = [];
  s.push("================================================================================");
  s.push("SECTION 2: BACKEND SERVER ARCHITECTURE (server.js)");
  s.push("================================================================================");
  s.push("");
  s.push("2.1 ARCHITECTURE, DEPENDENCIES & PORT BINDING");
  s.push("The file server.js is the primary Node.js HTTP server. It is implemented without external");
  s.push("framework dependencies like Express or Fastify to minimize overhead, cold-start latency,");
  s.push("and memory usage in containerized or low-cost hosting environments.");
  s.push("- Native Dependencies: 'http', 'fs', 'path', 'url'.");
  s.push("- Port Resolution: Defaults to process.env.PORT or port 3000.");
  s.push("- Listener Creation: http.createServer(async (req, res)) processes all requests.");
  s.push("");
  s.push("2.2 MIME TYPES & STATIC ASSET DELIVERY PIPELINE");
  s.push("The server defines a strict MIME_TYPES dictionary mapping extensions to Content-Type headers:");
  s.push("  - .html : 'text/html; charset=utf-8'");
  s.push("  - .css  : 'text/css; charset=utf-8'");
  s.push("  - .js   : 'application/javascript; charset=utf-8'");
  s.push("  - .json : 'application/json; charset=utf-8'");
  s.push("  - .png  : 'image/png'");
  s.push("  - .jpg / .jpeg : 'image/jpeg'");
  s.push("  - .svg  : 'image/svg+xml'");
  s.push("  - .webp : 'image/webp'");
  s.push("  - .ico  : 'image/x-icon'");
  s.push("");
  s.push("Path Sanitization & Security against Directory Traversal:");
  s.push("  - Input URL pathname is decoded and normalized via path.normalize().");
  s.push("  - Traversal characters like '../' and '..\\' are blocked by resolving against ROOT.");
  s.push("  - Root path '/' is mapped to 'frontend/index.html'.");
  s.push("  - Admin path '/admin' or '/admin/' is mapped to 'admin/index.html'.");
  s.push("  - If file exists, fs.createReadStream(filePath).pipe(res) streams bytes directly to client.");
  s.push("  - If file does not exist, returns HTTP 404 with text/plain '404 Not Found'.");
  s.push("");
  s.push("2.3 IN-MEMORY DATA STORE (memoryStore) SCHEMA");
  s.push("To ensure uninterrupted operation even when Firebase connection is lost or during rapid development,");
  s.push("server.js maintains an internal memoryStore holding active application state:");
  s.push("  - memoryStore.rewards: Array of system rewards and prizes.");
  s.push("  - memoryStore.requests: Array of cashout and prize redemption claims from users.");
  s.push("  - memoryStore.users: Dictionary indexed by user UID containing player profile and balance objects.");
  s.push("  - memoryStore.websiteTasks: Array of partner website click and browse tasks.");
  s.push("  - memoryStore.telegramTasks: Array of Telegram channel and group subscription tasks.");
  s.push("  - memoryStore.gameConfig: Global system settings { maintenanceMode: false, announcement: '' }.");
  s.push("  - memoryStore.levelsConfig: Custom overrides for Levels 1 to 1000.");
  s.push("  - memoryStore.notifications: In-game inbox notifications array { id, type, title, message, timestamp, read, actionText, actionTarget }.");
  s.push("  - memoryStore.antiFraud: Real-time anti-fraud engine cache:");
  s.push("      * antiFraud.processedNonces: Map of cryptographic UUID nonces -> timestamps preventing duplicate claims.");
  s.push("      * antiFraud.userCooldowns: Map of UID -> { [action]: timestamp } enforcing rate limits per action.");
  s.push("      * antiFraud.auditLog: Sliding window log (latest 100 entries) capturing IP, user-agent, action, payout, and risk state.");
  s.push("      * antiFraud.tapRates: Velocity metrics recording tap bursts to detect bot patterns.");
  s.push("  - memoryStore.identityIndex: Critical uniqueness lookup tables preventing multi-accounting:");
  s.push("      * identityIndex.telegram: Map of normalized tgId -> UID.");
  s.push("      * identityIndex.phone: Map of normalized phone -> UID.");
  s.push("      * identityIndex.email: Map of normalized email -> UID.");
  s.push("  - memoryStore.authConfig: Toggles for account uniqueness rules and allowed registration methods.");
  s.push("  - memoryStore.accountRequests: Pending user account resolution and identity binding claims.");
  s.push("  - memoryStore.fuelCellsConfig: Reactor cell configurations and purchase rules.");
  s.push("");
  s.push("2.4 UTILITY & HELPER FUNCTIONS IN server.js");
  s.push("1. normalizeTelegramId(id):");
  s.push("   - Lines: ~35-42");
  s.push("   - Parameters: id (string|number)");
  s.push("   - Logic: Converts id to string, removes whitespace, strips leading '@' if present.");
  s.push("   - Return: Sanitized string ID or empty string.");
  s.push("");
  s.push("2. normalizePhone(phone):");
  s.push("   - Lines: ~44-52");
  s.push("   - Parameters: phone (string)");
  s.push("   - Logic: Strips all non-numeric characters (+, -, spaces, parentheses).");
  s.push("   - Return: Clean numeric string representation of phone number.");
  s.push("");
  s.push("3. normalizeEmail(email):");
  s.push("   - Lines: ~54-61");
  s.push("   - Parameters: email (string)");
  s.push("   - Logic: Trims whitespace, casts to lowercase.");
  s.push("   - Return: Lowercased sanitized email string.");
  s.push("");
  s.push("4. parseRequestBody(req):");
  s.push("   - Lines: ~65-80");
  s.push("   - Parameters: req (IncomingMessage)");
  s.push("   - Logic: Buffers chunks of incoming request data via 'data' events up to 10MB safety limit.");
  s.push("     On 'end' event, attempts JSON.parse(body). If JSON is invalid, returns empty object {}");
  s.push("     safely without throwing unhandled exceptions.");
  s.push("   - Return: Promise resolving to parsed payload object.");
  s.push("");
  s.push("5. sendJson(res, statusCode, data):");
  s.push("   - Lines: ~82-95");
  s.push("   - Parameters: res (ServerResponse), statusCode (number), data (object)");
  s.push("   - Logic: Sets HTTP status code, Content-Type: application/json; charset=utf-8,");
  s.push("     and CORS headers: Access-Control-Allow-Origin: *, Access-Control-Allow-Methods: GET, POST, OPTIONS, DELETE,");
  s.push("     and writes JSON.stringify(data).");
  s.push("");
  s.push("2.5 REST API ENDPOINTS DETAILED WALKTHROUGH");
  s.push("1. GET /api/health");
  s.push("   - Returns { status: 'ok', timestamp: Date.now(), uptime: process.uptime() }.");
  s.push("   - Used by load balancers, monitoring daemons, and client connection checks.");
  s.push("");
  s.push("2. GET & POST /api/rewards");
  s.push("   - GET: Returns memoryStore.rewards array.");
  s.push("   - POST: Admin adds or updates a reward item. Validates title, cost, and stock.");
  s.push("");
  s.push("3. GET & POST /api/requests");
  s.push("   - GET: Returns pending prize redemption and Level 1000 Cash Prize claims.");
  s.push("   - POST: Player submits a new payout request with user details, payout method (UPI/Paytm), and amount.");
  s.push("");
  s.push("4. GET & POST /api/users");
  s.push("   - GET: Lists users with pagination and search query filtering by name, UID, or Telegram ID.");
  s.push("   - POST: Admin modifies user balance or toggles isBanned status.");
  s.push("");
  s.push("5. GET & POST & DELETE /api/tasks/website & /api/tasks/telegram");
  s.push("   - GET: Returns active list of engagement tasks.");
  s.push("   - POST: Admin creates a new task with title, url, rewardCoins, rewardKeys, and timerSeconds.");
  s.push("   - DELETE: Removes task by ID.");
  s.push("");
  s.push("6. GET & POST /api/game-config");
  s.push("   - GET: Returns global configuration: { maintenanceMode, announcement, appTitle }.");
  s.push("   - POST: Admin updates maintenance mode or emergency broadcast banner.");
  s.push("");
  s.push("7. GET & POST /api/levels-config");
  s.push("   - GET: Returns custom configurations for Levels 1 to 1000.");
  s.push("   - POST: Admin overrides XP required and reward drops for any level between 1 and 1000.");
  s.push("");
  s.push("8. POST /api/auth/telegram");
  s.push("   - Authenticates Telegram Mini App launch data.");
  s.push("   - Checks memoryStore.identityIndex.telegram for existing binding.");
  s.push("   - If new user, creates user record and registers telegram ID into index.");
  s.push("   - Returns user profile and session token.");
  s.push("");
  s.push("9. GET & POST /api/auth/check-identifier");
  s.push("   - Checks if a phone number, email, or Telegram ID is already bound to another account.");
  s.push("   - Prevents duplicate account creation and multi-accounting exploitation.");
  s.push("");
  s.push("10. POST /api/auth/link-credential");
  s.push("   - Binds a secondary identifier (e.g. phone or email) to an existing authenticated user profile.");
  s.push("   - Enforces unique indexing to ensure an identifier cannot be linked twice.");
  s.push("");
  s.push("11. GET & POST /api/auth/config");
  s.push("   - Manages authorization policies (e.g. requirePhoneVerification, allowGuestMode).");
  s.push("");
  s.push("12. GET /api/auth/duplicates & POST /api/auth/resolve-duplicate");
  s.push("   - Scans user database for conflicting credentials and allows admin to merge or unlink accounts.");
  s.push("");
  s.push("13. GET & POST /api/account_requests");
  s.push("   - Handles appeals and identity claim tickets submitted by players.");
  s.push("");
  s.push("14. POST /api/auth/migrate-indexes");
  s.push("   - Diagnostic utility that scans existing user records and rebuilds identityIndex hash maps.");
  s.push("");
  s.push("15. GET & POST /api/notifications & /api/notifications/mark-read");
  s.push("   - GET: Fetches active notifications for player's in-game inbox.");
  s.push("   - POST /api/notifications: Admin broadcast dispatcher sending Global, Event, Maintenance, or Reward alerts.");
  s.push("   - POST /api/notifications/mark-read: Updates read status for single or all notifications.");
  s.push("");
  s.push("16. POST /api/reward/claim (CRITICAL SERVER-AUTHORITATIVE REWARD VALIDATION)");
  s.push("   - Validates user identity, nonces, action cooldowns, and mathematical score boundaries.");
  s.push("   - Rejects replay attacks (HTTP 409) if a nonce was previously processed.");
  s.push("   - Enforces minimum cooldowns: Memory Match (12s), Coin Catcher (15s), Ads (8s), Streak (1hr).");
  s.push("   - Validates score caps and calculates authoritative coins/diamonds on server, updating memoryStore.users[uid].");
  s.push("   - Returns authoritative player balance to client to overwrite local optimistic values.");
  s.push("");
  s.push("17. POST /api/anti-fraud/verify-tap-session (TAP VELOCITY & AUTOCLICKER DETECTION)");
  s.push("   - Evaluates tap frequency: ratePerSec = tapCount / durationSeconds.");
  s.push("   - Automatically blocks impossible bot frequencies (>40 taps/sec) with HTTP 400 and logs security audit.");
  s.push("");
  s.push("18. GET & POST /api/fuel-cells-config & /api/fuel/buy");
  s.push("   - Server-authoritative fuel cell configuration and purchasing engine.");
  s.push("");
  return s.join('\n');
}

module.exports = { generateServerSection };
