// section6_7.js
function generateSecurityAndAlgorithmsSections() {
  let s = [];
  s.push("================================================================================");
  s.push("SECTION 6: SECURITY RULES & CONFIGURATIONS");
  s.push("================================================================================");
  s.push("");
  s.push("6.1 FIREBASE REALTIME DATABASE SECURITY (database.rules.json)");
  s.push("The Realtime Database enforces strict role-based access rules:");
  s.push("  - /users/$uid: Enforces that read and write operations are strictly permitted only");
  s.push("    if auth.uid === $uid. No user can read or overwrite another player's currency balances.");
  s.push("  - /leaderboard: Publicly readable (.read: true) so all players can view global rankings.");
  s.push("    Write operations are restricted to server-authenticated tokens or verified user score submissions.");
  s.push("  - /system: Administrative configuration node. Read-only for players; write restricted to admin auth.");
  s.push("");
  s.push("6.2 CLOUD FIRESTORE SECURITY (firestore.rules)");
  s.push("Firestore rules enforce granular object validations:");
  s.push("  - match /databases/{database}/documents");
  s.push("  - match /users/{userId}: allow read, write: if request.auth != null && request.auth.uid == userId;");
  s.push("  - match /settings/{document=**}: allow read: true; allow write: if request.auth.token.admin == true;");
  s.push("  - match /payout_requests/{requestId}: allow create: if request.auth != null; allow read, update: if request.auth.token.admin == true;");
  s.push("");
  s.push("6.3 CLOUD HOSTING & REWRITES (firebase.json & vercel.json)");
  s.push("  - Asset Caching: Static assets (images, web fonts, CSS) have Cache-Control headers set to");
  s.push("    'public, max-age=31536000, immutable' for instant repeat-visit rendering.");
  s.push("  - SPA Routing Rewrites: Any route not matching a physical file is rewritten to '/index.html'");
  s.push("    to enable client-side navigation without 404 errors.");
  s.push("  - API Proxying: Calls to /api/* are routed to serverless Node.js functions on Vercel.");
  s.push("");
  s.push("================================================================================");
  s.push("SECTION 7: END-TO-END EXECUTION FLOWS & ALGORITHMIC PROOFS");
  s.push("================================================================================");
  s.push("");
  s.push("7.1 TAP EXECUTION & POWER CONSUMPTION FLOW");
  s.push("  Step 1: User touches Quantum Reactor Orb (#reactorOrb).");
  s.push("  Step 2: Pointer event is intercepted by handleOrbTap(event) in home.js.");
  s.push("  Step 3: Validates reactor power: if gameState.reactor.currentEnergy < clickPower, plays error");
  s.push("          sawtooth tone and shows 'Core Depleted' floating alert.");
  s.push("  Step 4: Energy Deduction: gameState.reactor.currentEnergy -= clickPower.");
  s.push("  Step 5: Resource Award: gameState.player.coins += clickPower, gameState.player.xp += clickPower.");
  s.push("  Step 6: Particle Generation: Spawns floating neon number at clientX/clientY coordinates.");
  s.push("  Step 7: Feedback: Invokes sfx.playTapSound() and window.triggerTelegramHaptic('light').");
  s.push("  Step 8: Saves game state locally and queues debounced cloud sync.");
  s.push("");
  s.push("7.2 XP LEVEL ADVANCE & DARK GREEN FUEL MATH (LEVELS 1 TO 1000)");
  s.push("  - Linear XP Curve: Required XP for level L is computed as: requiredXp = L * 1000.");
  s.push("    * Level 1   : 1,000 XP");
  s.push("    * Level 500 : 500,000 XP");
  s.push("    * Level 1000: 1,000,000 XP");
  s.push("  - Dark Green Fuel Payout Formula (xp.js):");
  s.push("    * fuelCellsAwarded = Math.max(1, Math.min(200, Math.ceil(lvl / 5)))");
  s.push("    * Mathematical Progression:");
  s.push("      - Levels 1 to 5   : 1 Dark Green Fuel Cell");
  s.push("      - Levels 6 to 10  : 2 Dark Green Fuel Cells");
  s.push("      - Level 50        : 10 Dark Green Fuel Cells");
  s.push("      - Level 500       : 100 Dark Green Fuel Cells");
  s.push("      - Level 1000      : 200 Dark Green Fuel Cells (Max Cap)");
  s.push("  - Compulsory Video Ad Requirement:");
  s.push("    * Claiming any level reward requires watching exactly 1 rewarded ad via showRewardedAd().");
  s.push("  - Level 1000 Mega Cash Prize (10,000 Coins):");
  s.push("    * Unlocks when player reaches Level 1000.");
  s.push("    * Player watches 1,000 rewarded ads (tracked via xpState.watchedAds).");
  s.push("    * Upon reaching 1,000/1,000 ads, player submits payout claim for 10,000 Coins.");
  s.push("");
  s.push("7.3 GOAL MILESTONE PROGRESSION & EXPONENTIAL SCALING (GOALS 1 TO 1000)");
  s.push("  - 3-Emoji Progression Model: Requires Cards 🃏, Keys/Dandiyas 🥢, and Flowers/Tickets 🌸.");
  s.push("  - Mathematical Scaling Formula (goal.js):");
  s.push("    * progressRatio = (lvl - 1) / 999");
  s.push("    * curveFactor = Math.pow(progressRatio, 1.8)");
  s.push("    * cardsRequired   = Math.floor(20 + (200000 - 20) * curveFactor)");
  s.push("    * keysRequired    = Math.floor(50 + (500000 - 50) * curveFactor)");
  s.push("    * ticketsRequired = Math.floor(35 + (350000 - 35) * curveFactor)");
  s.push("  - Milestones:");
  s.push("    * Level 1   : 20 Cards, 50 Keys, 35 Tickets");
  s.push("    * Level 500 : ~54,000 Cards, ~135,000 Keys, ~94,500 Tickets");
  s.push("    * Level 1000: 200,000 Cards, 500,000 Keys, 350,000 Tickets");
  s.push("  - Level 1000 Mega Goal Prize:");
  s.push("    * Unlocks after completing Goal Level 1000 and watching 1,000 rewarded ads.");
  s.push("    * Awards Grand Loot: 100 Dandiyas/Keys, 75 Cards, 150 Flowers/Tickets, and 1,000 Coins.");
  s.push("");
  s.push("7.4 SCRATCH CARD CANVAS ALPHA-SUBSAMPLING MATH & 5-TIER PROBABILITIES");
  s.push("  - Strict Card Lock Enforcement:");
  s.push("    * singleCardState.hasActiveTicket must be true to scratch.");
  s.push("    * Without spending a card, clicking or dragging on the canvas is strictly blocked.");
  s.push("  - Canvas Erasing Physics (scratch.js):");
  s.push("    * Sets ctx.globalCompositeOperation = 'destination-out'.");
  s.push("    * Draws overlapping circles of radius 24px along the drag path.");
  s.push("  - Sub-sampling Alpha Check Algorithm (checkScratchCompletion()):");
  s.push("    * Instead of inspecting all 300x180 = 54,000 pixels (which would cause mobile frame drops),");
  s.push("      the engine sub-samples every 16th pixel (stride = 64 bytes in Uint8ClampedArray).");
  s.push("    * If transparent pixel count (alpha === 0) reaches >= 48% of total sample, triggers auto-reveal.");
  s.push("  - Strict 5-Tier Prize Distribution (SCRATCH_CARD_TIERS):");
  s.push("    * Tier 1: 1-2 Keys           -> 20% Probability");
  s.push("    * Tier 2: 10-20 Eggs         -> 50% Probability");
  s.push("    * Tier 3: 1-2 Tickets        -> 20% Probability");
  s.push("    * Tier 4: 10 Coins           ->  2% Probability");
  s.push("    * Tier 5: 50-75 Blue Coins   ->  8% Probability");
  s.push("    * Total Exact Probability    : 100%");
  s.push("  - On reveal completion, singleCardState.hasActiveTicket resets to false, requiring a new card.");
  s.push("");
  s.push("7.5 12-EGG HATCHERY PIGEONHOLE RANDOMIZATION & 11TH HATCH VICTORY PROOF");
  s.push("  - Grid Layout: 12 cyber eggs (4 columns x 3 rows). Cost: 1 Egg Coin per hatch.");
  s.push("  - 5 Win Categories (Collect 3 of any category to win):");
  s.push("    1. Keys        (3 Keys       -> Win 1 Key)");
  s.push("    2. Tickets     (3 Tickets    -> Win 1 Ticket)");
  s.push("    3. Cards       (3 Cards      -> Win 1 Card)");
  s.push("    4. Coins       (3 Coins      -> Win 10 Coins)");
  s.push("    5. Blue Coins  (3 Blue Coins -> Win 100 Blue Coins)");
  s.push("  - The 10-Item Randomization Rule:");
  s.push("    * At round initialization, the engine chooses targetWinner by weighted odds.");
  s.push("    * It generates a pool of 10 items consisting of exactly 2 items for each of the 5 categories:");
  s.push("      [Key, Key, Ticket, Ticket, Card, Card, Coin, Coin, BlueCoin, BlueCoin].");
  s.push("    * This 10-item pool is shuffled using the Fisher-Yates algorithm.");
  s.push("  - Mathematical Proof of Non-Completion in Hatches 1 to 10:");
  s.push("    * By the Pigeonhole Principle, since the maximum count of any category in the 10-item pool is 2,");
  s.push("      it is mathematically impossible for any category to reach 3 items during the first 10 hatches.");
  s.push("    * At hatch #10, all 5 collection meters will be at exactly 2/3 collected.");
  s.push("  - Guaranteed 11th Hatch Victory:");
  s.push("    * On the 11th hatch, the engine reveals the 3rd matching item for targetWinner.");
  s.push("    * That category hits 3/3, immediately triggering triggerEggWinCelebration().");
  s.push("    * Awards prize (e.g. 100 Blue Coins) and displays celebration modal.");
  s.push("");
  s.push("7.6 ANTI-FRAUD AD VERIFICATION & MULTI-DEVICE ACCOUNT UNIFICATION");
  s.push("  - Monetag Ad Validation: SDK invokes callback only upon complete video playback.");
  s.push("  - Multi-Identity Uniqueness: server.js checks normalized identity indexes (Telegram ID, phone, email).");
  s.push("    If any identifier is already claimed by another UID, registration or linking is blocked.");
  s.push("");
  s.push("7.7 MEMORY MATCH TIMING MATH, SPEED BONUS & STAR RATING PROOFS");
  s.push("  - 4 x 4 Matrix Shuffling: 16 cards comprising 8 identical emoji pairs (⚡, 💎, 🔋, 🚀, 🗝️, 🎫, 🥚, 🎴).");
  s.push("  - Card Flip State Engine: Tracks flippedCards array. Blocks clicks when flippedCards.length === 2 to prevent race conditions.");
  s.push("  - Countdown Timer Loop: 60-second window ticking via setInterval at 1000ms. If timer reaches 0, triggers gameOverMemory().");
  s.push("  - Multi-Factor Reward Algorithm:");
  s.push("    * Base Completion: 150 Coins, 1 Dungeon Key, 15 Diamonds.");
  s.push("    * Speed Bonus: timeBonusCoins = Math.max(0, timeRemaining) * 3.");
  s.push("    * Mistake Rating & Diamond Multiplier:");
  s.push("        - mistakes <= 2 : 3 Stars (⭐⭐⭐) & +60 Diamonds (Peak mastery bonus)");
  s.push("        - mistakes <= 5 : 2 Stars (⭐⭐)  & +35 Diamonds (Proficient solve)");
  s.push("        - mistakes > 5  : 1 Star  (⭐)   & +15 Diamonds (Standard solve)");
  s.push("  - Server Claim Verification: Client passes { timeRemaining, mistakes, stars } to POST /api/reward/claim.");
  s.push("    Server recalculates approved coins and diamonds using the exact same formula, rejecting any manipulated values.");
  s.push("");
  s.push("7.8 COIN CATCHER PHYSICS, HAZARDS, COMBO MULTIPLIER & SCORE BOUNDS");
  s.push("  - Object Spawning Matrix: Spawns every 600ms at randomized X coordinates (5% to 95% stage width).");
  s.push("  - Weighted Entity Distribution:");
  s.push("    * Gold Energy Coin (🪙): 55% frequency, speed 3.2px/frame, +10 Coins, increments combo.");
  s.push("    * Blue Energy Coin (💠): 25% frequency, speed 4.0px/frame, +25 Coins, increments combo.");
  s.push("    * Super Star (⭐): 8% frequency, speed 5.2px/frame, +50 Coins, +0.2x combo boost.");
  s.push("    * Bomb Hazard (💣): 12% frequency, speed 3.5px/frame, causes damage.");
  s.push("  - Life & Collision System: Player begins with 3 Lives (❤️❤️❤️). Catching a bomb triggers screen-shake CSS");
  s.push("    and deducts 1 Life. Losing all 3 lives immediately aborts the 30-second run.");
  s.push("  - Progressive Combo Multiplier: Increases by 0.1x per consecutive catch up to a max cap of 2.5x.");
  s.push("    Hitting a bomb hazard immediately resets the combo multiplier to 1.0x baseline.");
  s.push("  - Physical Speed Bounds Checking: Server enforces that in a 30s session, maximum achievable score");
  s.push("    is physically bounded (< 1500 coins and < 50 diamonds), instantly clamping suspicious values.");
  s.push("");
  s.push("7.9 IN-GAME NOTIFICATION DISPATCH, INBOX PERSISTENCE & DEEP-LINK ROUTING");
  s.push("  - Centralized Dispatch: Administrators compose announcements from the Admin Dashboard (admin/pages/dashboard/).");
  s.push("  - Inbox Notification Structure:");
  s.push("      { id, type, title, message, timestamp, read, actionText, actionTarget }.");
  s.push("  - Unread State Synchronization: App header polls or checks /api/notifications. If any unread message exists,");
  s.push("    the unread indicator pulse (#unreadBellDot) animates via CSS keyframes.");
  s.push("  - Contextual Deep-Link Routing:");
  s.push("    * Action buttons route players directly to specific game subsystems (e.g. actionTarget: 'streak'");
  s.push("      routes to #pageStreak; 'profile' routes to #pageProfile; 'reward' routes to #pageReward).");
  s.push("  - Single or Batch Mark-as-Read: Updates both server memoryStore and local storage to prevent duplicate alerts.");
  s.push("");
  s.push("7.10 ANTI-FRAUD ENGINE: REPLAY PREVENTION, COOLDOWNS & AUTOCLICKER ANOMALY DETECTION");
  s.push("  - Cryptographic Nonce Validation: Every reward claim generates a random UUID nonce. The server maintains");
  s.push("    memoryStore.antiFraud.processedNonces. If a claim arrives with an existing nonce, the server flags a Replay");
  s.push("    Attack and returns HTTP 409 Conflict without modifying user balances.");
  s.push("  - Granular Per-Action Cooldown Intervals (MIN_COOLDOWNS):");
  s.push("    * mini_game_memory : 12,000 ms (12 seconds minimum completion time)");
  s.push("    * mini_game_catcher: 15,000 ms (15 seconds minimum session duration)");
  s.push("    * ad_reward        :  8,000 ms (8 seconds minimum viewing time)");
  s.push("    * daily_streak     : 3,600,000 ms (1 hour between daily claims)");
  s.push("    * referral_claim   :  5,000 ms (5 seconds between squad payouts)");
  s.push("  - Tap Velocity Anomaly Detection (/api/anti-fraud/verify-tap-session):");
  s.push("    * ratePerSec = tapCount / durationSeconds.");
  s.push("    * Human multi-finger physical limit is ~20 to 25 taps/sec.");
  s.push("    * Rates exceeding 40 taps/sec are physically impossible on mobile screens and indicate automated software");
  s.push("      autoclickers. The server blocks the session with HTTP 400 and records the incident to security auditLog.");
  s.push("  - Multi-Identifier Uniqueness: identityIndex maps enforce that no Telegram ID, phone number, or email");
  s.push("    can belong to more than one player UID, shutting down multi-account referral fraud.");
  s.push("");
  s.push("7.11 SERVER-AUTHORITATIVE VS CLIENT-AUTHORITATIVE ARCHITECTURAL SEPARATION");
  s.push("  - Client-Authoritative (Safe UI & Visuals):");
  s.push("    * Active navigation tab and sub-tab selection.");
  s.push("    * Animation frame rendering, particle floaters, and screen-shake effects.");
  s.push("    * Sound effect toggles and volume preferences.");
  s.push("    * Selected cosmetic reactor ring skins.");
  s.push("    * Optimistic local counters for responsive 60 FPS tap feedback.");
  s.push("  - Server-Authoritative (Critical Economic Assets):");
  s.push("    * Gold coins, blue coins, diamonds, keys, spin tickets, and egg coins.");
  s.push("    * Level 1000 cashout payouts (10,000 Coins via UPI/Paytm).");
  s.push("    * Rewarded ad view payouts and energy refills.");
  s.push("    * Referral squad reward disbursements.");
  s.push("    * Achievement unlock certifications and badge granting.");
  s.push("    * Global leaderboard ranking scores.");
  s.push("  - Result: Player modifications to local window.gameState or localStorage cannot compromise game economics;");
  s.push("    any withdrawal, store purchase, or mini-game reward must be authorized by server.js.");
  s.push("================================================================================");
  s.push("                             END OF TECHNICAL GUIDE");
  s.push("================================================================================");
  return s.join('\n');
}

module.exports = { generateSecurityAndAlgorithmsSections };
