// section3_shared.js
// Detailed technical breakdown of frontend/shared/ modules
function generateSharedSection() {
  let s = [];
  s.push("================================================================================");
  s.push("SECTION 3: FRONTEND CORE & SHARED CLIENT SERVICES (frontend/shared/)");
  s.push("================================================================================");
  s.push("");
  s.push("3.1 REACTIVE GAME STATE & STORAGE ENGINE (frontend/shared/state.js)");
  s.push("The file state.js is the central state management core of the client application. It maintains");
  s.push("window.gameState as the single source of truth and manages persistence with localStorage and cloud.");
  s.push("");
  s.push("A. DETAILED SCHEMA OF window.gameState:");
  s.push("1. player: Object containing core account and currency balances:");
  s.push("   - uid: String. Unique identifier (Telegram ID or generated UUID).");
  s.push("   - name: String. Display name of the user.");
  s.push("   - level: Number. Current player level from 1 to 1000.");
  s.push("   - xp: Number. Accumulated lifetime experience points.");
  s.push("   - coins: Number. Standard gold coins earned from tapping and mini-games.");
  s.push("   - blueCoins: Number. Rare premium currency used in the Cyber Hatchery and shop.");
  s.push("   - diamonds: Number. Gem currency for special store items.");
  s.push("   - chestKeys: Number. Keys consumed to open Bronze, Silver, Gold, and Cyber mystery chests.");
  s.push("   - chestTickets: Number. Spin tickets consumed to rotate the Lucky Wheel.");
  s.push("   - scratchCards: Number. Cards required to unlock and scratch Quantum Scratch Tickets.");
  s.push("   - eggs: Number. Egg coins required to hatch eggs in the 12-Egg Cyber Hatchery.");
  s.push("   - isBanned: Boolean. Ban status flag.");
  s.push("   - referralCode: String. Unique referral code.");
  s.push("   - referredBy: String. UID of referring player.");
  s.push("   - referralCount: Number. Total players invited.");
  s.push("");
  s.push("2. reactor: Object managing the central quantum tap mechanics:");
  s.push("   - currentEnergy: Number. Available reactor power (0 to maxEnergy).");
  s.push("   - maxEnergy: Number. Total energy capacity (scales with generator upgrades).");
  s.push("   - clickPower: Number. Energy consumed and coins awarded per tap.");
  s.push("   - regenRate: Number. Energy restored per second (e.g. 3/s).");
  s.push("   - lastEnergyTimestamp: Number. Unix timestamp of last energy state calculation.");
  s.push("");
  s.push("3. energyGenerator: Object managing the 7-tier fuel injector:");
  s.push("   - level: Number. Generator level.");
  s.push("   - remainingSeconds: Number. Turbo boost countdown timer.");
  s.push("   - boostMultiplier: Number. Multiplier applied to energy regen during turbo boost.");
  s.push("   - fuelCells: Object containing counts for 7 colored fuel cells:");
  s.push("     { green: 0, darkgreen: 0, yellow: 0, orange: 0, red: 0, pink: 0, purple: 0 }.");
  s.push("");
  s.push("4. progression: Object managing global level milestones:");
  s.push("   - activeLevel: Number. Active milestone level (1 to 1000).");
  s.push("   - completedLevels: Object. Hash map of claimed level rewards { [lvl]: true }.");
  s.push("   - levelXp: Number. Current XP accumulated toward the next level.");
  s.push("");
  s.push("5. goalState: Object managing 3-emoji milestone roadmap (Goals 1 to 1000):");
  s.push("   - currentLevel: Number. Current goal milestone (1 to 1000).");
  s.push("   - currentSubtab: String. Active subview ('goals' | 'mega').");
  s.push("   - levelProgress: Object. Collected items for active goal: { cards: 0, keys: 0, tickets: 0 }.");
  s.push("   - claimedGoals: Object. Hash map of completed goals { [lvl]: true }.");
  s.push("   - megaWatchedAds: Number. Rewarded ads watched toward Level 1000 Mega Goal Reward (0 to 1000).");
  s.push("   - megaRewardClaimed: Boolean. True if Level 1000 Mega Goal Reward was claimed.");
  s.push("");
  s.push("6. xpState: Object managing XP level rewards (Levels 1 to 1000):");
  s.push("   - currentSubtab: String. Active subview ('levels' | 'mega').");
  s.push("   - claimedLevels: Object. Hash map of claimed level rewards { [lvl]: true }.");
  s.push("   - watchedAds: Number. Rewarded ads watched toward Level 1000 Mega Cash Prize (0 to 1000).");
  s.push("   - megaRewardClaimed: Boolean. True if 10,000 Coins Level 1000 Cash Prize was claimed.");
  s.push("   - seasonEndMs: Number. Timestamp marking current seasonal leaderboard end.");
  s.push("");
  s.push("7. eggHatchState: Object managing the 12-Egg Cyber Hatchery:");
  s.push("   - eggs: Array. 12 egg objects with { id, revealed, itemType, rewardDef }.");
  s.push("   - collected: Object. Collection meter tallies: { key: 0, ticket: 0, card: 0, coin: 0, blueCoin: 0 }.");
  s.push("   - hatchedCount: Number. Number of eggs hatched in active round (0 to 11).");
  s.push("   - targetWinner: String. Category selected to win on the 11th hatch ('key'|'ticket'|'card'|'coin'|'blueCoin').");
  s.push("   - first10Items: Array. Shuffled pool of 10 items (2 of each category) ensuring no 3-match occurs early.");
  s.push("   - gameCompleted: Boolean. True when 11th hatch celebration modal is triggered.");
  s.push("");
  s.push("8. singleCardState: Object managing Quantum Scratch Ticket:");
  s.push("   - hasActiveTicket: Boolean. Strict card lock flag. When false, canvas cannot be scratched.");
  s.push("   - currentReward: Object. Secret prize object revealed underneath the foil.");
  s.push("   - isRevealed: Boolean. True when >= 48% foil is cleared.");
  s.push("");
  s.push("B. FUNCTIONS IN state.js:");
  s.push("1. getDefaultGameState():");
  s.push("   - Returns fresh state object populated with default baseline values.");
  s.push("2. saveGame():");
  s.push("   - Serializes window.gameState to JSON and writes to localStorage under key 'energyTapSaveData'.");
  s.push("   - Calls debounced cloud sync (saveToCloudDebounced()) to replicate state to Firebase.");
  s.push("3. loadGame():");
  s.push("   - Reads 'energyTapSaveData' from localStorage.");
  s.push("   - Performs deep recursive merge with getDefaultGameState() so newly added fields are never undefined.");
  s.push("   - Calls calculateOfflineEnergy() to restore energy accumulated while the user was away.");
  s.push("4. calculateOfflineEnergy():");
  s.push("   - Computes elapsedSeconds = (Date.now() - reactor.lastEnergyTimestamp) / 1000.");
  s.push("   - Calculates restoredEnergy = elapsedSeconds * reactor.regenRate.");
  s.push("   - Caps currentEnergy at maxEnergy and updates lastEnergyTimestamp.");
  s.push("5. resetGame():");
  s.push("   - Clears localStorage and reinitializes gameState to defaults.");
  s.push("6. claimServerAuthoritativeReward(action, payload):");
  s.push("   - Core security bridge enforcing server authority over game economy.");
  s.push("   - Generates unique UUID nonce (nonce_timestamp_random) preventing replay attacks.");
  s.push("   - Posts claim payload to /api/reward/claim for server validation (cooldowns & mathematical bounds).");
  s.push("   - Adopts verified server balances for player coins, diamonds, and keys directly into gameState.");
  s.push("   - If offline or network unavailable, queues claim and safely syncs upon reconnect.");
  s.push("");
  s.push("--------------------------------------------------------------------------------");
  s.push("3.2 APPLICATION CONTROLLER, ROUTER & IN-GAME NOTIFICATION CENTER (frontend/shared/app.js)");
  s.push("--------------------------------------------------------------------------------");
  s.push("The file app.js serves as the master orchestrator, router, audio synthesizer, and notification center.");
  s.push("");
  s.push("A. DOM NODE CACHING (DOM):");
  s.push("To prevent DOM query thrashing during 60 FPS tap animations, app.js caches frequently accessed");
  s.push("elements at initialization:");
  s.push("  - DOM.headerLevel, DOM.headerCoins, DOM.headerDiamonds, DOM.headerEnergy: Header pill counters.");
  s.push("  - DOM.headerInboxBtn, DOM.unreadBellDot: In-game inbox bell icon and pulsating red unread badge dot.");
  s.push("  - DOM.notificationModalOverlay, DOM.notificationItemsList: Notification sheet overlay and card feed.");
  s.push("  - DOM.appMain: Master viewport container holding all 27 page views.");
  s.push("  - DOM.bottomNav: Floating cyber navigation bar.");
  s.push("");
  s.push("B. PAGE NAVIGATION ENGINE (switchPage(pageId)):");
  s.push("  - Parameter: pageId (string). E.g. 'home', 'scratch', 'egg', 'memoryMatch', 'coinCatcher', 'xp', 'goal'.");
  s.push("  - Step 1: Removes 'active' class from all .page-view elements.");
  s.push("  - Step 2: Capitalizes pageId to find container #page<CapitalizedId> (e.g. #pageMemoryMatch, #pageCoinCatcher).");
  s.push("  - Step 3: Adds 'active' class to target container, triggering CSS opacity transition.");
  s.push("  - Step 4: Updates active state on bottom navigation bar icons.");
  s.push("  - Step 5: Triggers lifecycle entry hooks if defined by the target page (e.g. initMemoryMatch(),");
  s.push("            initCoinCatcher(), initScratchPage(), renderEggPageContent(), renderGoalsList(), renderLevelsList()).");
  s.push("  - Step 6: Plays subtle page transition audio via sfx.playTapSound(440).");
  s.push("");
  s.push("C. IN-GAME NOTIFICATION CENTER INBOX SUBSYSTEM:");
  s.push("  - fetchNotifications(): Queries GET /api/notifications; counts unread items; toggles #unreadBellDot pulse.");
  s.push("  - toggleNotificationInbox(show): Displays or dismisses sliding bottom-sheet modal (#notificationModalOverlay).");
  s.push("  - filterNotifications(category): Filters feed by 'all', 'reward', or 'system' with active filter pill styling.");
  s.push("  - renderNotifications(): Generates styled cards with title, relative timestamp, message, type badge, and CTA button.");
  s.push("  - markAllNotificationsRead(): Submits POST /api/notifications/mark-read { all: true } and clears unread indicators.");
  s.push("  - openNotificationTarget(target): Closes inbox modal and routes player directly to target page view.");
  s.push("");
  s.push("D. PROCEDURAL WEB AUDIO SYNTHESIZER (window.sfx):");
  s.push("Built using HTML5 Web Audio API (AudioContext). Eliminates network lag and external audio file requests.");
  s.push("  1. playTapSound(frequency = 520):");
  s.push("     - Creates OscillatorNode with 'triangle' waveform and GainNode.");
  s.push("     - Plays ultra-short 0.04s burst with exponential decay envelope.");
  s.push("  2. playLevelUpSound():");
  s.push("     - Plays an arpeggiated 4-tone victory chord (C5: 523Hz, E5: 659Hz, G5: 784Hz, C6: 1046Hz)");
  s.push("       staggered by 70ms intervals with smooth decay.");
  s.push("  3. playCoinSound():");
  s.push("     - Generates high-pitch 987Hz sine wave tone simulating metallic coin pickup.");
  s.push("  4. playErrorSound():");
  s.push("     - Generates low-pitch 140Hz sawtooth wave indicating insufficient energy, coins, or cards.");
  s.push("  5. playWhooshSound():");
  s.push("     - Simulates air whoosh for spinning wheels and modal transitions using filtered noise.");
  s.push("");
  s.push("E. TELEGRAM WEBAPP HAPTICS (window.triggerTelegramHaptic(type)):");
  s.push("Checks if window.Telegram?.WebApp?.HapticFeedback is available and invokes native device vibrations:");
  s.push("  - Impact feedback: 'light', 'medium', 'heavy', 'rigid', 'soft'.");
  s.push("  - Notification feedback: 'success', 'warning', 'error'.");
  s.push("");
  s.push("F. TOAST & MODAL ENGINES:");
  s.push("  - showFloatingToast(message, type = 'info'): Spawns floating neon pill at top of screen.");
  s.push("    Automatically animates slide-down, stays for 2.8s, and fades out.");
  s.push("  - openTabModal(title, contentHtml): Creates centered glassmorphic dialog with backdrop blur.");
  s.push("  - closeTabModal(): Smoothly dismisses modal dialog.");
  s.push("");
  s.push("G. MASTER UPDATE LOOP (updateUI()):");
  s.push("Runs on state modifications and periodic 1000ms ticker:");
  s.push("  - Refreshes header pill counters (Level, Coins, Diamonds, Energy).");
  s.push("  - Updates active page UI components.");
  s.push("  - Calls energy regeneration ticker.");
  s.push("");
  s.push("--------------------------------------------------------------------------------");
  s.push("3.3 CLOUD DATABASE & REALTIME SYNCHRONIZATION (frontend/shared/firebase-service.js)");
  s.push("--------------------------------------------------------------------------------");
  s.push("Manages bidirectional synchronization between local client state and Google Firebase cloud stores.");
  s.push("- Supported Backends: Dual support for Firebase Realtime Database (RTDB) and Cloud Firestore.");
  s.push("- saveToCloudDebounced(): Debounces save requests by 2500ms to avoid saturating write quotas during fast tapping.");
  s.push("- saveToCloudImmediate(): Flushes state immediately to /users/{uid} on critical events (level up, cashout claim).");
  s.push("- Offline Resilience: Attaches 'online' and 'offline' window listeners. If connection drops, mutations");
  s.push("  are held in a local sync queue and automatically pushed when connection recovers.");
  s.push("- fetchCloudData(uid): Reads player profile upon app boot. Compares cloud timestamp with local timestamp.");
  s.push("  If cloud data is newer, updates local state.");
  s.push("- syncLeaderboard(): Automatically pushes player's lifetime coin balance and level to /leaderboard collection.");
  s.push("");
  s.push("--------------------------------------------------------------------------------");
  s.push("3.4 AD NETWORK INTEGRATION & SIMULATOR (frontend/shared/ad-service.js)");
  s.push("--------------------------------------------------------------------------------");
  s.push("Integrates Monetag Rewarded Interstitial advertising with client-side fraud prevention.");
  s.push("- Official Monetag Zone ID: 11677609.");
  s.push("- showRewardedAd(onSuccess, onFail):");
  s.push("  Step 1: Checks if Monetag SDK function window.show_11677609 exists.");
  s.push("  Step 2: If available, triggers ad overlay. On successful view completion, triggers onSuccess().");
  s.push("  Step 3: If blocked by adblocker, network timeout, or SDK failure, automatically falls back");
  s.push("          to startAdSimulation() so the player is NEVER stuck or prevented from leveling up.");
  s.push("- startAdSimulation(zoneId, title, desc, onComplete):");
  s.push("  Displays an in-app simulated ad player modal with a high-tech progress countdown (typically 5s),");
  s.push("  ensuring game continuity in offline testing environments.");
  s.push("");
  s.push("--------------------------------------------------------------------------------");
  s.push("3.5 GLOBAL DESIGN SYSTEM & CYBER THEME TOKENS (frontend/shared/common.css)");
  s.push("--------------------------------------------------------------------------------");
  s.push("Defines the cyberpunk visual styling and layout tokens:");
  s.push("- Obsidian Space Backgrounds: --bg-primary: #040919, --bg-card: rgba(15, 23, 42, 0.75).");
  s.push("- Neon Energy Accents: --emerald: #10b981, --cyan: #06b6d4, --purple: #8b5cf6, --gold: #fbbf24.");
  s.push("- Glassmorphism: backdrop-filter: blur(16px), border: 1px solid rgba(255, 255, 255, 0.08).");
  s.push("- Typography: 'Plus Jakarta Sans' for primary UI headings, 'JetBrains Mono' for numbers and crypto counters.");
  s.push("- Animation Keyframes: @keyframes pulse-glow, @keyframes spin-slow, @keyframes float-up.");
  s.push("");
  return s.join('\n');
}

module.exports = { generateSharedSection };
